# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171222_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.BooleanField(),
        ),
    ]
