# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171223_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
